---
name: bosh-cron

releases:
- name: bosh-cron
  version: 0.1.0
- name: bpm
  version: 0.2.0
  url: git+https://github.com/cloudfoundry-incubator/bpm-release

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: bosh-cron
  azs: [z1]
  instances: 1
  jobs:
  - name: bosh-cron
    release: bosh-cron
    properties:
      director:
        host: ((director_ip))
        tls:
          cert:
            ca: ((director_ssl.ca))
        client: ((director_client))
        client_secret: ((director_client_secret))
  vm_type: default
  stemcell: default
  networks:
  - name: default

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm
